"""phase 0-8 consolidated schema with topic areas

Revision ID: e95afa549a34
Revises: 
Create Date: 2026-04-21 13:10:18.985606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e95afa549a34'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cohorts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('visibility_rules', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('series', sa.String(length=4), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year', 'series', name='uq_session_year_series')
    )
    op.create_table('syllabi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('syllabus_id', sa.Integer(), nullable=True),
    sa.Column('cohort_id', sa.Integer(), nullable=True),
    sa.Column('learning_style_profile', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cohort_id'], ['cohorts.id'], ),
    sa.ForeignKeyConstraint(['syllabus_id'], ['syllabi.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('papers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('syllabus_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('supports_digital_input', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['syllabus_id'], ['syllabi.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('syllabus_id', 'number', name='uq_paper_syllabus_number')
    )
    op.create_table('rate_limits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('endpoint', sa.String(length=64), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'day', 'endpoint', name='uq_rl_user_day_endpoint')
    )
    op.create_table('topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('syllabus_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('short_name', sa.String(length=32), nullable=True),
    sa.Column('color_class', sa.String(length=32), nullable=False),
    sa.Column('area_code', sa.String(length=16), nullable=True),
    sa.Column('area_name', sa.String(length=80), nullable=True),
    sa.Column('syllabus_ref', sa.String(length=24), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['syllabus_id'], ['syllabi.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('syllabus_id', 'number', name='uq_topic_syllabus_number')
    )
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_topics_area_code'), ['area_code'], unique=False)

    op.create_table('error_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'topic_id', name='uq_ep_user_topic')
    )
    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('content_html', sa.Text(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('past_papers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('syllabus_id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('variant', sa.Integer(), nullable=False),
    sa.Column('source_pdf_path', sa.String(length=512), nullable=False),
    sa.Column('formula_sheet_ref', sa.String(length=512), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['syllabus_id'], ['syllabi.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('syllabus_id', 'paper_id', 'session_id', 'variant', name='uq_pp_full')
    )
    op.create_table('revision_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('generated_content_html', sa.Text(), nullable=False),
    sa.Column('style_used', sa.String(length=32), nullable=False),
    sa.Column('cache_key', sa.String(length=64), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'topic_id', 'style_used', name='uq_revnote_ut_style')
    )
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('past_paper_id', sa.Integer(), nullable=False),
    sa.Column('question_number', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=False),
    sa.Column('images', sa.JSON(), nullable=True),
    sa.Column('marks_total', sa.Integer(), nullable=True),
    sa.Column('difficulty', sa.String(length=16), nullable=True),
    sa.Column('extraction_status', sa.String(length=24), nullable=False),
    sa.ForeignKeyConstraint(['past_paper_id'], ['past_papers.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subparts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('letter', sa.String(length=4), nullable=False),
    sa.Column('body_html', sa.Text(), nullable=False),
    sa.Column('answer_schema', sa.String(length=16), nullable=False),
    sa.Column('correct_answer', sa.JSON(), nullable=True),
    sa.Column('mcq_choices', sa.JSON(), nullable=True),
    sa.Column('canonical_method', sa.Text(), nullable=True),
    sa.Column('marking_alternatives', sa.JSON(), nullable=True),
    sa.Column('marks', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subpart_id', sa.Integer(), nullable=False),
    sa.Column('submitted_answer', sa.JSON(), nullable=True),
    sa.Column('working_photo_path', sa.String(length=512), nullable=True),
    sa.Column('ocr_transcript', sa.Text(), nullable=True),
    sa.Column('verdict', sa.String(length=24), nullable=True),
    sa.Column('error_tags', sa.JSON(), nullable=True),
    sa.Column('diagnostic_feedback_html', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['subpart_id'], ['subparts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attempts')
    op.drop_table('subparts')
    op.drop_table('questions')
    op.drop_table('revision_notes')
    op.drop_table('past_papers')
    op.drop_table('notes')
    op.drop_table('error_profiles')
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_topics_area_code'))

    op.drop_table('topics')
    op.drop_table('rate_limits')
    op.drop_table('papers')
    op.drop_table('users')
    op.drop_table('syllabi')
    op.drop_table('sessions')
    op.drop_table('cohorts')
    # ### end Alembic commands ###
